---
# Playbook to install HAProxy proxy
- import_playbook: flush_jumphost_key.yaml

- name: Provision Nginx based proxy
  hosts: haproxy
  roles:
    - opentelekomcloud.server_common
    - opentelekomcloud_infra.haproxy

